# Generated by Django 5.0.6 on 2024-06-21 17:53

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='None', max_length=1000, null=True)),
                ('place_name', models.CharField(default='Unspecified', max_length=100)),
                ('date', models.DateField(default=datetime.date(2024, 6, 21))),
                ('time', models.TimeField(default=datetime.time(17, 53, 40, 135253))),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('category', models.CharField(default='others', max_length=100, verbose_name='')),
                ('images', models.ManyToManyField(blank=True, to='ruby.image')),
            ],
        ),
    ]
