# Generated by Django 5.0.4 on 2024-04-11 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 20, 28, 46, 81606)),
        ),
    ]
