# Generated by Django 5.0.6 on 2024-06-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruby', '0002_alter_event_time'),
        ('ruby', '0003_event_time_alter_event_date'),
    ]

    operations = [
    ]
